<?php

/**
 * @file
 * Contains vue_controls.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vue_controls_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vue_controls module.
    case 'help.page.vue_controls':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Vue Controls') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function vue_controls_theme() {
  return [
    'vue_controls' => [
      'render element' => 'children',
    ],
  ];
}
