<?php

 function vue_controls_theme($existing, $type, $theme, $path) {
   return [
     'vue_controls_incrementer' => [
       'variables' => [
         'entity_id' => '',
         'bundle' => '',
         'field_name' => '',
         'field_value' => '',
         'field_label' => '',
       ],
    ],
  ];
}

function vue_controls_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'vue_controls/vue_controls';
}
